steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: 3.0
      bundler-cache: true

  - name: Install dependencies
    run: bundle install

  - name: Build Jekyll site
    run: bundle exec jekyll build
